# Site settings
title: ngMigrate by Kendo UI
email: todd@toddmotto.com
description: >
  ngMigrate is a project to migrate your existing Angular 1 knowledge into Angular 2.
baseurl: ""
url: "http://ngmigrate.telerik.com"
fixedNav: 'true' # true or false
theme: green # green, blue, orange, purple, grey
twitterUsername: toddmotto
githubUsername: toddmotto
paginate: 2
gems: [jekyll-paginate]
# Build settings
permalink: /:title
markdown: kramdown
include: [_pages]
exclude: [_site, _scripts, node_modules, TEMPLATE.txt, CONTRIBUTING.md, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
